### ISSUE TITLE
SQLServer Connection is null when trying to select data with QueryDslJdbcTemplate but OK with  JdbcTemplate  and native SQLQuery

### ISSUE THREAD

**Issue by gokhanoner** [spring-projects/spring-data-jdbc-ext#13]
Hi

I'm testing with Spring boot 1.2.0 + spring data jdbc 1.1.0 + Querydsl 3.6

I initilalized QueryDSlTemplate like below:

```
@Bean
public SQLTemplates sqlTemplates() {
    return SQLServer2008Templates.builder()
            .printSchema() // to include the schema in the output
            .quote() // to quote names
            .newLineToSingleSpace() // to replace new lines with single space in the output
            .build();   
}

@Bean(name = "qt1")
public QueryDslJdbcTemplate queryDslJdbcTemplate(JdbcTemplate jdbcTemplate, SQLTemplates sqlTemplates) {
    return new QueryDslJdbcTemplate(jdbcTemplate, sqlTemplates);
}

@Bean(name = "qt2")
public QueryDslJdbcTemplate queryDslJdbcTemplate(DataSource dataSource) {
    return new QueryDslJdbcTemplate(dataSource);
}
```

I'm testing offset() so need SQL2008Template.

anyway, test code is below:

```
@Autowired
DataSource dataSource;
@Autowired
SQLTemplates dialect;
@Autowired
@Qualifier("qt1")
QueryDslJdbcTemplate template;
@Autowired
@Qualifier("qt2")
QueryDslJdbcTemplate template2;

@Autowired
JdbcTemplate jdbcTemplate;

@Test
public void queryDslTest() throws SQLException {
    QFxmatch fxmatch = new QFxmatch("fx");

    SQLQuery query = new SQLQuery(dataSource.getConnection(), dialect);
    List<Fxmatch> list = query.from(fxmatch)
        .where(fxmatch.type.eq("A")
        .and(fxmatch.msgtype.eq("300")))
        .orderBy(fxmatch.sasrn.asc())
        .limit(5)
        .offset(2)
        .list(fxmatch);

    log.info(list.toString());
}

@Test
public void queryDslTestSpring()  {
    try {

        List<Map<String, Object>> sdd = jdbcTemplate.queryForList("SELECT * FROM FXMATCH");

        QFxmatch fxmatch = new QFxmatch("fx");

        List<Fxmatch> list = template2.newSqlQuery().from(fxmatch)
            .where(fxmatch.type.eq("A")
            .and(fxmatch.msgtype.eq("300")))
            .orderBy(fxmatch.sasrn.asc())
            .limit(3)
            .list(fxmatch);

        log.info(list.toString());
    } catch (Exception e) {
        e.printStackTrace();
    }
}
```

queryDslTest() method works perfect, gave me the data. See that I'm usign autowired datasource.

queryDslTestSpring(), jdbcTemplate query workking OK, but template2.newSqlQuery(), or template.newSqlQuery(), gave below error:

<code>
java.lang.NullPointerException
    at com.mysema.query.sql.AbstractSQLQuery.list(AbstractSQLQuery.java:308)
    at com.global.swift.fx.QueryDSLTest.queryDslTestSpring(QueryDSLTest.java:98)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:73)
    at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)
    at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:73)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:217)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
    at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) 
</code>

I look to the source code, and Connection object is null.

**Comment by trisberg** [comment]
If you can share a small sample project that exhibits this problem I can take a look

**Comment by gokhanoner** [comment]
Hi,

Please find below repo as test case. I used H2 Db, results are same:

https://github.com/gokhanoner/querydsl_test

**Comment by gokhanoner** [comment]
Hi,

I've added a new test case & I believe I found the issue.

in test3_springQueryDslJdbcTemplate, I build the query like this:
List<Users> users = queryDslJdbcTemplate.newSqlQuery().from(qUsers)
				.where(qUsers.enabled.eq(true))
				.list(qUsers);

in test4_springQueryDslJdbcTemplate, I changed it like this:
		
SQLQuery sqlQuery = queryDslJdbcTemplate.newSqlQuery()
						.from(qUsers)
						.where(qUsers.enabled.eq(true));
		
		List<Users> users = queryDslJdbcTemplate.query(sqlQuery, qUsers);
